"""Create threads and thread_items tables

Revision ID: 967623eee52b
Revises: 27fb9ff82798
Create Date: 2025-12-25 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '967623eee52b'
down_revision = '27fb9ff82798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)

    op.create_table('thread_items',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_items_thread_id'), 'thread_items', ['thread_id'], unique=False)
    op.create_index(op.f('ix_thread_items_user_id'), 'thread_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_items_user_id'), table_name='thread_items')
    op.drop_index(op.f('ix_thread_items_thread_id'), table_name='thread_items')
    op.drop_table('thread_items')
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###